stages:
  split_data:
    cmd: python src/split_data.py
    deps:
    - data/raw_data/raw.csv
    - src/split_data.py
    outs:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - data/processed_data/y_test.csv
    - data/processed_data/y_train.csv
  normalize_data:
    cmd: python src/norm_data.py
    deps:
    - data/processed_data/X_test.csv
    - data/processed_data/X_train.csv
    - src/norm_data.py
    outs:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/X_train_scaled.csv
    - models/scaler.pkl
  gridsearch_model:
    cmd: python src/gridsearch_model.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - src/gridsearch_model.py
    outs:
    - models/best_params.pkl
  train_model:
    cmd: python src/train_model.py
    deps:
    - data/processed_data/X_train_scaled.csv
    - data/processed_data/y_train.csv
    - models/best_params.pkl
    - src/train_model.py
    outs:
    - models/model.pkl
  evaluate_model:
    cmd: python src/evaluate_model.py
    deps:
    - data/processed_data/X_test_scaled.csv
    - data/processed_data/y_test.csv
    - models/model.pkl
    - src/evaluate_model.py
    outs:
    - data/predictions.csv
    - metrics/scores.json
